### ISSUE TITLE
Input component label gone?

### ISSUE THREAD

**Issue by HFolkertH** [cincheo/daquota#53] opened 2022-07-12 18:55 UTC
If i start a new blanco project and add an input-component, then i can not add a label to that input anymore.
Older project stilll have the label attribute, but new/blanco projects don’t.

**Comment by renaudpawlak** [comment] 2022-07-12 19:48
Ouch... really? I don't see that bug. Do you have a screenshot? Maybe try to clear you browser cache?

**Comment by renaudpawlak** [comment] 2022-07-12 19:49
Can you open the developper mode and see if there are errors in the console? (command+option+i on most browsers)

**Comment by renaudpawlak** [comment] 2022-08-04 15:45
Can we close this issue? If there is still a problem, can you send me the JSON code of the faulty component please?

**Comment by renaudpawlak** [comment] 2022-09-28 11:03
Unable to reproduce.

**Closed as completed by renaudpawlak** 2022-09-28 11:03 UTC
